Repository hasboeuf/yogit, pull requests merged in 2019-07, with the labels that each got.

#2 Fix duplicated "on" typo
  yogit/tests/test_scrum.py
  yogit/yogit/settings.py
Labels: wording

#4 Added pr list per orga
  yogit/api/queries.py
  yogit/api/statement.py
  yogit/api/statements.py
  yogit/tests/test_pr.py
  yogit/yogit/pullrequest.py
Labels: enhancement

#5 Reinforce scrum report cmd
  yogit/tests/test_scrum.py
  yogit/yogit/scrum_report.py
Labels: bug

#6 Improve UX
  requirements/yogit.txt
  setup.py
  yogit/api/queries.py
  yogit/storage/storage.py
  yogit/tests/conftest.py
  yogit/tests/test_account.py
  yogit/tests/test_br.py
  yogit/tests/test_pr.py
  yogit/tests/test_rv.py
  yogit/utils/spinner.py
  yogit/yogit/account.py
  yogit/yogit/logger.py
  yogit/yogit/paths.py
  yogit/yogit/scrum_report.py
  yogit/yogit/settings.py
Labels: enhancement

#7 Added `yogit rv list` cmd
  yogit/api/queries.py
  yogit/api/statements.py
  yogit/tests/test_rv.py
  yogit/yogit/review.py
Labels: enhancement

#8 Add yogit update check
  yogit/__init__.py
  yogit/tests/test_update_checker.py
  yogit/yogit/account.py
  yogit/yogit/branch.py
  yogit/yogit/checks.py
  yogit/yogit/cli.py
  yogit/yogit/logger.py
  yogit/yogit/pullrequest.py
  yogit/yogit/review.py
  yogit/yogit/scrum.py
  yogit/yogit/update_checker.py
Labels: enhancement
